apiVersion: v1
kind: Secret
metadata:
  name: {{ include "web.secretname" . }}
  labels:
    {{- include "web.labels" . | nindent 4 }}
type: Opaque
data:
  REDIS_URL: {{ .Values.appSecret.redisUrl | b64enc | quote }}
