apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api.cmname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
data:
  DBHOST: {{ .Values.db.host | quote }}
  DB: {{ .Values.db.name | quote }}
  DBPORT: {{ .Values.db.port | quote }}
  PGSSLMODE: "require"
