apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "api.pdbname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "api.selectorLabels" . | nindent 6 }}
