apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.secretname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
type: Opaque
data:
  DBUSER: {{ .Values.dbSecret.user | b64enc | quote }}
  DBPASS: {{ .Values.dbSecret.password | b64enc | quote }}
